#!/bin/sh

### This script removes all files created by grunt
### Run this if you want to refresh the build

# TODO: Fix this
alias findexc='find . -not \( -path ./node_modules -prune -o -path ./public_www/scripts/libs -prune -o -path ./.git -prune \) -print0 '

echo "Removing map files"
findexc -name "*.map" | xargs -rt --null -- echo

echo "Removing min files"
findexc \( -name "*.min.js" -o -name "*.min.css" -o -name "*.min.html" \) | xargs -rt --null -- echo

echo "Removing JS files"
findexc -name "*.js" | xargs -rt --null -- echo

echo "Removing CSS files"
findexc -name "*.css" | xargs -rt --null -- echo

echo "Removing .sass-cache"
findexc -name ".sass-cache" | xargs -rt --null -- echo # rm -r
