#!/bin/sh

### This script removes all files created by grunt
### Run this if you want to refresh the build

# Exceptions
exc="node_modules\|libs"

echo "Removing map files"
find . -name "*.map" -type f | grep -v "$exc" | xargs -r rm

echo "Removing min files"
find . -type f -name "*.min.js" -o -name "*.min.css" -o -name "*.min.html" | grep -v "$exc" | xargs -r rm

echo "Removing JS files"
find . -name "*.js"  -type f | grep -v "$exc" | xargs -r rm

echo "Removing CSS files"
find . -name "*.css" -type f | grep -v "$exc" | xargs -r rm

echo "Removing .sass-cache"
find . -name ".sass-cache" -type d | grep -v "$exc" | xargs -r -- rm -r
