// Generated by CoffeeScript 1.10.0
angular.module('epsilonApp').controller('epsilonPanelController', function($location, $scope) {
  var panelCtrl;
  panelCtrl = this;
  panelCtrl.session = {
    id: 0
  };
  $.post('/api/panel/get', {
    get: 'session'
  }, function(data) {
    console.log(data);
    panelCtrl.session.id = data.id;
    return $scope.$apply();
  });
});
