// Generated by CoffeeScript 1.10.0
angular.module('epsilonApp').config(function($routeProvider) {
  var templateRoot, tr;
  templateRoot = "/templates";
  tr = templateRoot;
  return $routeProvider.when('/', {
    templateUrl: tr + "/index.html"
  }).when('/login', {
    templateUrl: tr + "/login.html"
  }).when('/lost-password', {
    templateUrl: tr + "/lost-password.html"
  }).when('/register', {
    templateUrl: tr + "/register.html"
  }).when('/about', {
    templateUrl: tr + "/about.html"
  }).otherwise({
    redirectTo: "/"
  });
});
