// Generated by CoffeeScript 1.10.0
angular.module('epsilonApp').config(function($routeProvider) {
  var templateRoot, tr;
  templateRoot = "/templates";
  tr = templateRoot;
  return $routeProvider.when('/', {
    templateUrl: tr + "/index"
  }).when('/login', {
    templateUrl: tr + "/login"
  }).when('/lost-password', {
    templateUrl: tr + "/lost-password"
  }).when('/register', {
    templateUrl: tr + "/register"
  }).when('/about', {
    templateUrl: tr + "/about"
  }).when('/panel/', {
    templateUrl: tr + "/panel/index",
    controller: 'epsilonPanelController',
    controllerAs: 'panelCtrl'
  }).otherwise({
    redirectTo: "/"
  });
});
